In [43]:
import torch

In [44]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 5 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))


In [45]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [46]:
## Calculate the output of this network using the weights and bias tensors
print(features)
print(weights)
print(bias)
aman  = (features).T
out =  torch.sum((aman*weights)+bias)
output = activation(out)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[0.3177]])


In [47]:

y = activation(torch.mm(features, weights.view(5,1)) + bias)

In [48]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)

# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))


In [49]:
n_input

3

In [50]:
# xx = f1((features*w1)+ b)
# yy = f1((xx * w2) + b2 )

a = activation(torch.mm(features, W1)+ B1)
output =  activation(torch.mm(a,W2)+ B2)
output

tensor([[0.3171]])

## Numpy to Torch and back

Special bonus section! PyTorch has a great feature for converting between Numpy arrays and Torch tensors. To create a tensor from a Numpy array, use `torch.from_numpy()`. To convert a tensor to a Numpy array, use the `.numpy()` method.

In [51]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.86301895, 0.08325759, 0.44117497],
       [0.02263522, 0.80557185, 0.05050236],
       [0.00850915, 0.86108927, 0.36741245],
       [0.20556395, 0.48576123, 0.44752294]])

In [52]:
b = torch.from_numpy(a)
b

tensor([[0.8630, 0.0833, 0.4412],
        [0.0226, 0.8056, 0.0505],
        [0.0085, 0.8611, 0.3674],
        [0.2056, 0.4858, 0.4475]], dtype=torch.float64)

In [53]:
b.numpy()

array([[0.86301895, 0.08325759, 0.44117497],
       [0.02263522, 0.80557185, 0.05050236],
       [0.00850915, 0.86108927, 0.36741245],
       [0.20556395, 0.48576123, 0.44752294]])

In [54]:
# Multiply PyTorch Tensor by 2, in place
b.mul_(2)

tensor([[1.7260, 0.1665, 0.8823],
        [0.0453, 1.6111, 0.1010],
        [0.0170, 1.7222, 0.7348],
        [0.4111, 0.9715, 0.8950]], dtype=torch.float64)

In [55]:
# Numpy array matches new values from Tensor
a

array([[1.72603791, 0.16651517, 0.88234993],
       [0.04527045, 1.6111437 , 0.10100472],
       [0.0170183 , 1.72217854, 0.73482491],
       [0.41112789, 0.97152246, 0.89504589]])